[package]
name = "aspargus"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chksum-hash-md5 = "0.0.0"
ollama-rs = "0.1.8"
directories = "5.0.1"
anyhow = "1.0.80"
log = "0.4.21"
simple_logger = "4.3.3"
glob = "0.3.1"
tokio = { version = "1.36.0", features = ["full"] }
base64 = "0.22.0"
md5 = "0.7.0"
image = "0.25.0"
rayon = "1.9.0"
clap = { version = "4.5.2", features = ["cargo"] }
serde_json = "1.0.114"
serde = { version = "1.0.197", features = ["derive"] }
chrono = "0.4.37"
